/**
 * Evidence metadata for the 100 original curriculum nodes.
 *
 * Row shape: [kind, constructs, "cv/tr/tx", measurementMethod, knownLimitations,
 *             citationKeys, retentionModelOverride?]
 *
 * cv = construct validity (does the thing exist and can it be measured)
 * tr = trainability      (does deliberate practice move it)
 * tx = transfer          (does moving it change anything else)
 *
 * These three are separated on purpose. Almost every popular claim about brain
 * training comes from silently sliding from the first to the third. Several
 * rows below are deliberately unflattering about the node they describe.
 */
export const NODE_META = {
  // ── Linguistic ────────────────────────────────────────────────────────────
  "ling-vocab-depth": [
    "knowledge",
    ["crystallized-knowledge", "reading-writing"],
    "strong/strong/moderate",
    "Production rather than recognition: use each target word correctly in an unseen context, and track the true retention rate of your spaced-repetition deck.",
    "Vocabulary is domain-bounded. Learning 500 rhetorical terms does not raise general verbal ability, and recognition outruns production by a wide margin — a word you can define is not yet a word you can deploy.",
    ["carroll1993", "nation2013", "cepeda2006"],
  ],
  "ling-reading": [
    "competency",
    ["reading-writing", "crystallized-knowledge"],
    "strong/strong/moderate",
    "Comprehension probes on unseen passages: state the main claim, the load-bearing assumption, and what evidence would falsify it.",
    "Comprehension is mostly knowledge-bound. You cannot read well in a domain you know nothing about, and generic 'reading strategy' training plateaus after a handful of sessions.",
    ["willingham2017", "dunlosky2013", "carroll1993"],
  ],
  "ling-writing": [
    "competency",
    ["reading-writing"],
    "strong/strong/moderate",
    "Rubric-scored responses to unseen prompts (claim clarity, evidence quality, structure) plus the revision distance between your first draft and your final one.",
    "Writing quality is substantially domain-specific: strong expository skill in one field transfers only partly to another, and self-assessment of one's own prose is unreliable.",
    ["graham2008", "barnett2002", "dunning2011"],
  ],
  "ling-rhetoric": [
    "competency",
    ["reading-writing", "socio-emotional"],
    "moderate/moderate/emerging",
    "Blind audience ratings of persuasiveness on a held-out position, plus the steelman test: can you argue the opposing side to the same standard?",
    "Persuasion outcomes depend heavily on audience, topic and status. Measured gains rarely generalise across all three, and rhetorical skill is orthogonal to being right.",
    ["kahneman2011", "barnett2002"],
  ],
  "ling-speaking": [
    "competency",
    ["reading-writing", "socio-emotional"],
    "moderate/strong/emerging",
    "Recorded impromptu talks scored for structure, filler rate and time-to-point, ideally with a listener rating comprehension afterwards.",
    "Speaking anxiety and speaking skill are separable problems. Fluency gains under low-stakes practice frequently shrink under real audience pressure.",
    ["ericsson1993", "macnamara2014"],
  ],
  "ling-second-language": [
    "competency",
    ["crystallized-knowledge", "auditory-processing", "reading-writing"],
    "strong/strong/moderate",
    "CEFR-style can-do checks: comprehension of unscripted native-speed speech, and production under time pressure without preparation.",
    "The 'bilingual executive advantage' is contested and has repeatedly failed to replicate. Learn a language for the language, not for a cognitive bonus.",
    ["nation2013", "waterhouse2006", "salaGobet2019"],
  ],

  // ── Logical-Mathematical ──────────────────────────────────────────────────
  "log-deduction": [
    "ability",
    ["fluid-reasoning"],
    "strong/moderate/emerging",
    "Untimed validity judgements on unseen syllogisms and conditional-reasoning items, scored for content-independent accuracy.",
    "People reason far better with familiar content than with abstract rules. Training typically improves the trained format and leaks very little into everyday argument.",
    ["wason1968", "carroll1993", "salaGobet2019"],
  ],
  "log-proof": [
    "competency",
    ["fluid-reasoning", "quantitative"],
    "strong/strong/moderate",
    "Produce a correct proof of an unseen statement at a stated difficulty band; score validity and gap-freeness, not elegance.",
    "Proof skill is bound to the mathematical domain you practise in. Fluency in ε-δ analysis says little about your combinatorics.",
    ["polya1945", "barnett2002"],
  ],
  "log-probability": [
    "competency",
    ["quantitative", "fluid-reasoning"],
    "strong/strong/moderate",
    "Brier score on your own dated, resolved predictions, plus base-rate and conditional-probability items presented in natural frequency format.",
    "Fluency with probability notation is not calibrated judgement under uncertainty. Neuron tracks the two separately because people routinely have one without the other.",
    ["gigerenzer1995", "tetlock2015", "lichtenstein1982"],
  ],
  "log-estimation": [
    "competency",
    ["quantitative", "fluid-reasoning"],
    "moderate/strong/moderate",
    "Order-of-magnitude accuracy on unseen Fermi targets, with the true value checked afterwards and the error logged in log units.",
    "Estimation accuracy is partly a knowledge effect: you estimate well in domains whose anchor quantities you already hold. Improvement is often anchor acquisition wearing a reasoning costume.",
    ["lewis1990", "tetlock2015"],
  ],
  "log-algorithmic": [
    "competency",
    ["fluid-reasoning", "quantitative"],
    "moderate/strong/moderate",
    "Solve unseen problems at a fixed difficulty with correctness and complexity both scored; track time-to-first-correct-approach separately from time-to-solution.",
    "Competitive-programming skill is a narrow expertise. It predicts other algorithmic work well and general problem solving much less well than practitioners assume.",
    ["newell1972", "ericsson1993", "barnett2002"],
  ],
  "log-systems": [
    "competency",
    ["fluid-reasoning"],
    "emerging/moderate/speculative",
    "Produce a stock-and-flow or causal-loop model of an unfamiliar system that predicts a behaviour you did not already know, then check the prediction.",
    "Systems thinking has weak measurement standards and almost no controlled training evidence. It is easy to mistake a pretty diagram for understanding.",
    ["meadows2008", "salaGobet2019"],
  ],

  // ── Spatial ───────────────────────────────────────────────────────────────
  "spa-visualization": [
    "ability",
    ["visual-processing"],
    "strong/moderate/emerging",
    "Timed accuracy on unseen visualisation items (fold-and-punch, cross-section prediction), plus self-report of image vividness kept clearly separate from accuracy.",
    "Reported vividness and actual accuracy dissociate — aphantasic people often perform normally on spatial tasks. Do not treat the felt experience as the measurement.",
    ["uttal2013", "shepard1971", "carroll1993"],
  ],
  "spa-rotation": [
    "ability",
    ["visual-processing"],
    "strong/strong/moderate",
    "Timed Shepard–Metzler style rotation items at a fixed angular disparity; track accuracy and the slope of response time against rotation angle.",
    "Spatial training reliably improves spatial tasks and the gains are durable, but transfer to STEM outcomes is modest and inconsistent across studies.",
    ["shepard1971", "uttal2013"],
  ],
  "spa-navigation": [
    "competency",
    ["visual-processing"],
    "moderate/moderate/emerging",
    "Pointing accuracy to unseen landmarks after traversing a novel route, and the fidelity of a sketch map drawn from memory.",
    "Survey-level knowledge of one city does not generalise to another. The famous hippocampal findings describe extreme, sustained expertise, not weekend practice.",
    ["atkinson2011", "uttal2013"],
  ],
  "spa-drawing": [
    "competency",
    ["visual-processing", "psychomotor"],
    "moderate/strong/emerging",
    "Blind comparison of your drawing against the reference for proportion and angle error — not for style.",
    "Observational drawing trains perception of a specific class of subject. Improvement on faces does not carry to mechanical parts without separate practice.",
    ["edwards2012", "kellman2009"],
  ],
  "spa-diagramming": [
    "competency",
    ["visual-processing", "fluid-reasoning"],
    "moderate/moderate/moderate",
    "Give a reader only your diagram and ask them to answer questions about the system it depicts; score their answers, not your satisfaction with the drawing.",
    "A diagram that is legible to its author is often opaque to anyone else. Diagram quality is only measurable through another person's comprehension.",
    ["larkin1987", "tufte2001"],
  ],
  "spa-modeling": [
    "competency",
    ["visual-processing", "psychomotor"],
    "moderate/strong/emerging",
    "Dimensional accuracy of the finished object against the intended design, plus the count of iterations needed to reach tolerance.",
    "CAD fluency and physical making are different skills that share a vocabulary. Neither reliably transfers to abstract spatial reasoning tests.",
    ["uttal2013", "schmidt2011"],
  ],

  // ── Musical ───────────────────────────────────────────────────────────────
  "mus-pitch": [
    "ability",
    ["auditory-processing"],
    "strong/strong/emerging",
    "Adaptive two-alternative pitch discrimination: the smallest interval you can reliably distinguish, in cents, at threshold.",
    "Discrimination thresholds improve substantially with practice, but this is perceptual learning of a narrow stimulus class. It does not make you musical, and it does not transfer to language or intelligence measures.",
    ["micheyl2006", "sala2017music", "kellman2009"],
  ],
  "mus-rhythm": [
    "ability",
    ["auditory-processing", "psychomotor"],
    "strong/strong/emerging",
    "Tapping asynchrony against a metronome (mean and variance of the offset), measured at several tempi including uncomfortable ones.",
    "Sensorimotor synchronisation improves with training and is measurable to the millisecond, but claims that rhythm training raises reading or maths ability are not supported.",
    ["repp2013", "sala2017music"],
  ],
  "mus-harmony": [
    "knowledge",
    ["auditory-processing", "crystallized-knowledge"],
    "moderate/strong/emerging",
    "Identify function and voice-leading in unseen scores and by ear; predict the next chord before hearing it and score the hit rate.",
    "Theoretical knowledge and aural recognition are separate stores. Many people can analyse a progression on paper that they cannot hear.",
    ["micheyl2006", "carroll1993"],
  ],
  "mus-instrument": [
    "competency",
    ["psychomotor", "auditory-processing"],
    "strong/strong/emerging",
    "Error rate and tempo ceiling on a passage at fixed difficulty, recorded rather than remembered.",
    "Deliberate practice explains a substantial but far from complete share of performance variance — around a quarter in music. Hours alone predict less than practitioners are told.",
    ["ericsson1993", "macnamara2014", "schmidt2011"],
  ],
  "mus-transcription": [
    "competency",
    ["auditory-processing", "working-memory"],
    "moderate/strong/emerging",
    "Note-level accuracy against the source recording, with the number of replays needed logged as a separate difficulty signal.",
    "Transcription accuracy is heavily genre-bound: fluency with functional pop harmony collapses on atonal or microtonal material.",
    ["micheyl2006", "ericsson1995"],
  ],
  "mus-improvisation": [
    "competency",
    ["auditory-processing", "fluid-reasoning"],
    "emerging/moderate/speculative",
    "Blind listener ratings of coherence and surprise on recorded takes, plus a count of distinct ideas developed rather than merely stated.",
    "Musical creativity has weak measurement standards. Neuroimaging findings about improvisation are interesting but do not license claims about general creative ability.",
    ["berkowitz2010", "runco2012", "baer2015"],
  ],

  // ── Bodily-Kinesthetic ────────────────────────────────────────────────────
  "kin-proprioception": [
    "ability",
    ["psychomotor"],
    "moderate/moderate/emerging",
    "Joint position matching with vision occluded, and balance time on an unstable surface with eyes closed.",
    "Proprioceptive acuity is joint- and task-specific. Ankle training does not improve shoulder position sense.",
    ["schmidt2011"],
    "physical",
  ],
  "kin-coordination": [
    "competency",
    ["psychomotor"],
    "strong/strong/emerging",
    "Timed accuracy on a standard manual task (pegboard, juggling catches, instrument passage) recorded at a fixed difficulty.",
    "Motor skills are notoriously specific. Skill at one bimanual task predicts another only when they share the same movement structure.",
    ["schmidt2011", "barnett2002"],
    "physical",
  ],
  "kin-strength": [
    "enabler",
    ["psychomotor"],
    "strong/strong/moderate",
    "Load and rep progression on compound movements, plus resting heart rate and recovery quality as supporting signals.",
    "Exercise supports cognition through sleep, mood and cerebrovascular health — real effects, but indirect and modest. Strength itself is not a cognitive ability.",
    ["mujika2000", "hillman2008"],
    "physical",
  ],
  "kin-motor-learning": [
    "competency",
    ["psychomotor"],
    "strong/strong/moderate",
    "Retention and transfer tests taken at least 24 hours after practice — performance during a session is a poor guide to what was learned.",
    "The conditions that make practice feel productive (blocked, constant, heavily cued) are often the ones that produce the least durable learning.",
    ["schmidt2011", "soderstrom2015", "bjork1994"],
    "physical",
  ],
  "kin-breath": [
    "enabler",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "Resting respiratory rate, breath-hold tolerance, and heart-rate recovery after a deliberate stressor.",
    "Slow-breathing effects on arousal are real and immediate; claims about lasting personality or attention change from breathwork alone are not supported.",
    ["farb2015", "vandam2016"],
    "physical",
  ],
  "kin-craft": [
    "competency",
    ["psychomotor", "visual-processing"],
    "moderate/strong/emerging",
    "Tolerance achieved on the finished piece and the scrap rate across attempts.",
    "Craft skill is material-specific. Competence in wood does not carry to metal beyond general workshop habits.",
    ["ericsson1993", "schmidt2011"],
    "physical",
  ],

  // ── Interpersonal ─────────────────────────────────────────────────────────
  "inter-active-listening": [
    "social",
    ["socio-emotional"],
    "moderate/strong/moderate",
    "The other person confirms your summary of their position before you respond — count how often your first summary is accepted without correction.",
    "Feeling attentive is not the same as being accurate. Only the speaker's confirmation counts as a measurement here.",
    ["rogers1957", "ickes1993"],
  ],
  "inter-perspective": [
    "social",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "Predict a specific person's stated preference or reaction in advance, then check with them. Score the hit rate, not the effort.",
    "Perspective-taking effort often increases confidence more than accuracy, and can backfire when it substitutes a model of the person for asking them.",
    ["ickes1993", "josephNewman2010"],
  ],
  "inter-nonverbal": [
    "social",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "Accuracy on standardised affect-recognition item sets, plus real-world checks where you state a read and verify it.",
    "Accuracy at reading nonverbal cues is real but modest, and popular 'body language' claims wildly exceed the evidence. Deception detection in particular is close to chance for nearly everyone.",
    ["ambady1992", "hall2009"],
  ],
  "inter-collaboration": [
    "social",
    ["socio-emotional"],
    "emerging/moderate/emerging",
    "Team-level outcomes plus teammate ratings of whether your contributions unblocked or duplicated theirs.",
    "Collaboration quality is confounded with the team you happen to be in. Individual measurement is weak and easily attributed to the wrong person.",
    ["josephNewman2010", "diehl1987"],
  ],
  "inter-teaching": [
    "competency",
    ["reading-writing", "socio-emotional"],
    "moderate/strong/moderate",
    "Test the learner, not yourself: their unaided performance after your explanation is the only real score.",
    "Preparing to teach improves the teacher's own learning reliably; whether your students learn more is a separate claim requiring separate evidence.",
    ["fiorella2016", "bloom1984"],
  ],
  "inter-negotiation": [
    "social",
    ["socio-emotional"],
    "moderate/strong/moderate",
    "Objective outcomes against your stated reservation value and target, recorded before the negotiation rather than rationalised after.",
    "Single outcomes are dominated by situation and leverage. Only a run of negotiations with pre-registered targets says anything about skill.",
    ["fisher2011", "thompson2020"],
  ],

  // ── Intrapersonal ─────────────────────────────────────────────────────────
  "intra-introspection": [
    "meta",
    ["socio-emotional"],
    "emerging/emerging/speculative",
    "Predict your own future behaviour or state, write it down, and score it later. Self-report alone is not a measurement.",
    "Introspective reports correlate weakly with behaviour. It is entirely possible to become more confident in your self-model without becoming more accurate.",
    ["dunning2011", "kruger1999", "barrett2017"],
  ],
  "intra-metacognition": [
    "meta",
    ["executive-control"],
    "moderate/moderate/emerging",
    "Calibration gap: predicted versus actual performance on a task before you attempt it, tracked over many attempts.",
    "Metacognitive monitoring is measurable; metacognitive *control* — actually changing study behaviour in response — is much harder to move and is what matters.",
    ["flavell1979", "kornell2007", "metcalfe2009"],
  ],
  "intra-values": [
    "meta",
    ["socio-emotional"],
    "emerging/emerging/speculative",
    "Consistency between stated priorities and where your calendar and money actually went, checked monthly.",
    "Values clarification is intuitively compelling and thinly evidenced. Treat it as a decision aid, not as a measured capability.",
    ["locke2002"],
  ],
  "intra-attention": [
    "meta",
    ["executive-control", "working-memory"],
    "moderate/moderate/emerging",
    "Uninterrupted work-block duration and self-caught mind-wandering rate, plus performance on an attention-control task at a fixed time of day.",
    "Attention control is a real and important individual difference. Whether it can be trained in adults, as opposed to protected by environment design, remains contested.",
    ["unsworth2014", "ophir2009", "mrazek2013", "vandam2016"],
  ],
  "intra-growth-mindset": [
    "meta",
    ["socio-emotional"],
    "emerging/emerging/emerging",
    "Behavioural, not attitudinal: after a failure, does the next attempt happen, and does it change strategy?",
    "Effect sizes in large preregistered trials are small and concentrated in specific groups. Treat mindset as one modest lever, not a foundation.",
    ["yeager2019", "sisk2018"],
  ],
  "intra-solitude": [
    "enabler",
    [],
    "speculative/emerging/speculative",
    "Count of deliberate unstimulated reflection sessions and whether any produced a written insight you acted on.",
    "This is a practice Neuron recommends on weak evidence. Reflection after experience has some support; solitude as a trainable capability essentially has none.",
    ["schoen2013", "vandam2016"],
  ],

  // ── Naturalistic ──────────────────────────────────────────────────────────
  "nat-observation": [
    "competency",
    ["visual-processing"],
    "moderate/strong/emerging",
    "Blind re-identification: can you distinguish two similar specimens after the fact using only the features you recorded?",
    "Observational skill is taxon-specific perceptual learning. Expertise in birds does not transfer to fungi.",
    ["kellman2009", "atran1998"],
  ],
  "nat-taxonomy": [
    "knowledge",
    ["crystallized-knowledge"],
    "strong/strong/moderate",
    "Unaided identification of unseen specimens to a stated rank, with retention checked weeks later.",
    "Classification knowledge is a memory store like any other and decays on the same schedule. It is not a general categorisation ability.",
    ["atran1998", "cepeda2006"],
  ],
  "nat-ecology": [
    "knowledge",
    ["crystallized-knowledge", "fluid-reasoning"],
    "moderate/moderate/emerging",
    "Predict a second-order consequence of a perturbation in a real local system, then look for the evidence.",
    "Ecological reasoning shares the measurement problems of systems thinking: plausible narratives are easy, checkable predictions are hard.",
    ["meadows2008", "atran1998"],
  ],
  "nat-pattern-recognition": [
    "ability",
    ["visual-processing", "fluid-reasoning"],
    "moderate/moderate/speculative",
    "Detect a genuine regularity in field data and state in advance what would show it to be coincidence.",
    "Humans over-detect patterns in noise. Without a falsification step this node trains confidence rather than accuracy.",
    ["kellman2009", "wason1968"],
  ],
  "nat-seasonality": [
    "knowledge",
    ["crystallized-knowledge"],
    "moderate/strong/emerging",
    "Dated predictions of local phenological events, scored against what actually happened.",
    "Local calendars do not transfer between regions and are shifting with the climate faster than intuition updates.",
    ["atran1998"],
  ],
  "nat-navigation-natural": [
    "competency",
    ["visual-processing"],
    "emerging/moderate/speculative",
    "State your heading from natural cues alone, then check it against a compass. Log the error in degrees.",
    "Natural navigation is a charming skill with almost no controlled training literature. The measurement above is honest; the evidence base is thin.",
    ["gooley2011", "atkinson2011"],
  ],

  // ── EQ · Self-Awareness ───────────────────────────────────────────────────
  "eqa-emotion-granularity": [
    "social",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "Differentiation index computed from repeated same-day emotion ratings: low correlation between distinct emotion terms means you are genuinely distinguishing them.",
    "Granularity predicts better regulation outcomes in correlational work; the causal direction is not established, and the labels are culture-bound.",
    ["kashdan2015", "barrett2017"],
  ],
  "eqa-interoception": [
    "ability",
    ["socio-emotional"],
    "moderate/emerging/speculative",
    "Heartbeat counting or detection accuracy, kept strictly separate from your confidence in that accuracy.",
    "Interoceptive accuracy and interoceptive confidence dissociate, and most training moves the latter. Reported improvement here is weak evidence.",
    ["farb2015", "vandam2016"],
  ],
  "eqa-trigger-mapping": [
    "meta",
    ["socio-emotional"],
    "emerging/moderate/emerging",
    "Predict which situations this week will provoke a reaction, then check your log against what actually happened.",
    "Retrospective trigger narratives are easy to construct and hard to falsify. Only the prediction version is evidence.",
    ["gross2015", "barrett2017"],
  ],
  "eqa-bias-awareness": [
    "meta",
    ["executive-control"],
    "moderate/moderate/emerging",
    "Catch a bias in your own reasoning *before* the decision is made, and record the correction you applied.",
    "Knowing a bias by name does not remove it. Only structured procedures applied at the decision point show durable effects, and even those are domain-limited.",
    ["morewedge2015", "kahneman2011", "graber2012"],
  ],
  "eqa-feedback-seeking": [
    "meta",
    ["socio-emotional"],
    "moderate/strong/moderate",
    "Count of specific, disconfirming feedback requests made, and whether a behaviour actually changed afterwards.",
    "Roughly a third of feedback interventions make performance worse, particularly when feedback targets the self rather than the task.",
    ["kluger1996", "hattie2007"],
  ],
  "eqa-narrative-audit": [
    "meta",
    ["socio-emotional"],
    "speculative/emerging/speculative",
    "Write the story you tell about a recurring situation, then list what evidence would contradict it and go looking.",
    "This is a therapeutic technique borrowed without its clinical structure. Neuron includes it as a reflective prompt, not as a measured capability.",
    ["barrett2017", "schoen2013"],
  ],

  // ── EQ · Self-Regulation ──────────────────────────────────────────────────
  "eqr-impulse-control": [
    "meta",
    ["executive-control"],
    "strong/moderate/emerging",
    "Stop-signal or go/no-go performance, plus real-world counts of intended-versus-emitted responses in a chosen situation.",
    "Laboratory inhibition and real-world self-control correlate weakly. Improvement on a stop-signal task is not evidence that you interrupt people less.",
    ["miyake2000", "diamond2013", "diamond2016"],
    "executive-habit",
  ],
  "eqr-reappraisal": [
    "meta",
    ["socio-emotional"],
    "strong/strong/moderate",
    "Rate arousal before and after applying a reappraisal, and track how often you reach for it unprompted.",
    "Reappraisal works well for situations you cannot change and poorly for those you can, where it can suppress useful action signals.",
    ["gross2015", "webb2012"],
    "executive-habit",
  ],
  "eqr-distress-tolerance": [
    "meta",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "Time spent in a deliberately uncomfortable but safe state before escape, plus whether the task at hand was still completed.",
    "Tolerance is situation-specific and easy to confuse with dissociation or suppression, which have worse downstream outcomes.",
    ["gross2015", "webb2012"],
    "executive-habit",
  ],
  "eqr-recovery": [
    "enabler",
    ["executive-control", "working-memory"],
    "strong/strong/strong",
    "Sleep duration and regularity from a wearable or diary, alongside next-day performance on a fixed vigilance or arithmetic probe.",
    "This is one of the few nodes where transfer evidence is genuinely strong — but the direction that replicates is the negative one: sleep loss reliably degrades cognition. Extra sleep beyond sufficiency does not keep adding gains.",
    ["lim2010", "hillman2008"],
    "physical",
  ],
  "eqr-habit-design": [
    "meta",
    ["executive-control"],
    "strong/strong/moderate",
    "Adherence rate of a specific implementation intention (when X, I will do Y) over four weeks, not intention strength.",
    "Implementation intentions have robust medium effects for simple, well-specified behaviours and much weaker ones for complex or aversive goals.",
    ["gollwitzer1999", "wood2016", "locke2002"],
    "executive-habit",
  ],
  "eqr-delayed-gratification": [
    "meta",
    ["executive-control"],
    "moderate/moderate/emerging",
    "Choice behaviour on real stakes with a delay, recorded at the moment of choosing rather than recalled later.",
    "The famous marshmallow findings shrink substantially once family background is controlled. Delay behaviour reflects circumstances and trust as much as capacity.",
    ["mischel1989", "watts2018"],
    "executive-habit",
  ],

  // ── EQ · Social Awareness ─────────────────────────────────────────────────
  "eqs-empathic-accuracy": [
    "social",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "Infer what someone was thinking or feeling at a specific moment, then have them score you against their own account.",
    "Empathic accuracy is measurable but modest, and motivation moves it more than skill does. Effort does not guarantee accuracy.",
    ["ickes1993", "josephNewman2010"],
  ],
  "eqs-compassion": [
    "social",
    ["socio-emotional"],
    "emerging/moderate/emerging",
    "Behavioural: costly helping actually taken, not compassion felt.",
    "Self-reported compassion is inflated and weakly related to helping behaviour. Treat felt warmth as unmeasured.",
    ["gross2015", "vandam2016"],
  ],
  "eqs-social-context": [
    "social",
    ["socio-emotional"],
    "emerging/moderate/emerging",
    "Write your read of a room's state before acting, then check it with a participant afterwards.",
    "Situational reads are heavily influenced by your own status and mood in the room, and confirmation is rarely sought.",
    ["ambady1992", "hall2009"],
  ],
  "eqs-cultural-fluency": [
    "knowledge",
    ["crystallized-knowledge", "socio-emotional"],
    "moderate/strong/moderate",
    "Predict a norm violation before it happens in an unfamiliar setting, then verify with someone from that culture.",
    "Cultural knowledge is specific and perishable, and national-level frameworks obscure enormous within-culture variation.",
    ["atran1998"],
  ],
  "eqs-listening-depth": [
    "social",
    ["socio-emotional"],
    "emerging/moderate/emerging",
    "State the unstated concern you think you heard, and count how often the speaker confirms it unprompted.",
    "Subtext inference is where confident over-reading does the most damage. Without confirmation this trains projection.",
    ["rogers1957", "ickes1993"],
  ],
  "eqs-boundaries-read": [
    "social",
    ["socio-emotional"],
    "speculative/emerging/speculative",
    "Instances where you named a limit you inferred and were told you had read it correctly.",
    "There is no established measurement for this construct. It is included because it is practically important, not because it is well evidenced.",
    ["hall2009", "ickes1993"],
  ],

  // ── EQ · Relationship Management ──────────────────────────────────────────
  "eqm-trust-building": [
    "social",
    ["socio-emotional"],
    "emerging/moderate/emerging",
    "Commitments made versus commitments kept, counted over months, plus whether people bring you problems early.",
    "Trust is an outcome of a relationship, not a skill you hold. Attributing it to individual training is a stretch.",
    ["fisher2011", "josephNewman2010"],
  ],
  "eqm-conflict": [
    "social",
    ["socio-emotional"],
    "moderate/strong/moderate",
    "Whether the substantive issue was resolved and whether the relationship survived — both scored, separately, afterwards.",
    "Conflict outcomes depend on the other party's behaviour, which you do not control. Single instances are uninformative.",
    ["fisher2011", "thompson2020"],
  ],
  "eqm-repair": [
    "social",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "Count of ruptures explicitly named and repaired, with the other person confirming the repair landed.",
    "Repair attempts that the other person does not accept are not repairs. Self-assessment here is unusually unreliable.",
    ["gross2015", "fisher2011"],
  ],
  "eqm-influence": [
    "social",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "Behaviour change you predicted in advance actually occurring, distinguished from agreement expressed in the room.",
    "Influence measurement is confounded with authority and timing. Ethical influence is a constraint on this node, not a measurable property of it.",
    ["kahneman2011", "thompson2020"],
  ],
  "eqm-mentoring": [
    "social",
    ["socio-emotional"],
    "moderate/moderate/emerging",
    "The mentee's outcomes and their unaided ability to do what you taught, months later.",
    "Mentoring effects are slow, confounded with selection, and easily claimed without evidence.",
    ["fiorella2016", "bloom1984"],
  ],
  "eqm-network": [
    "social",
    ["socio-emotional"],
    "emerging/moderate/speculative",
    "Reciprocity: contacts where value flowed both ways in the last year, not contact count.",
    "Network metrics are easy to game and easy to mistake for relationship quality. Treat this as a maintenance habit, not an ability.",
    ["josephNewman2010"],
  ],

  // ── Fluid · Abstract Reasoning ────────────────────────────────────────────
  "gf-pattern-abstraction": [
    "ability",
    ["fluid-reasoning"],
    "strong/emerging/speculative",
    "Accuracy on unseen matrix-style items under a time limit, using item sets you have not previously drilled.",
    "This is the ability most resistant to training. Practice reliably improves matrix-test scores through strategy and familiarity; the evidence that it raises the underlying ability is weak and repeatedly contradicted.",
    ["carroll1993", "melby2016", "salaGobet2019", "simons2016"],
  ],
  "gf-analogy": [
    "competency",
    ["fluid-reasoning"],
    "strong/moderate/moderate",
    "Map a solved problem onto an unseen one from a different domain and state the correspondence explicitly before solving.",
    "Spontaneous analogical transfer is rare without an explicit prompt — the classic finding is that most people fail to use a hint they have just read.",
    ["gick1983", "markman2013", "hofstadter2013"],
  ],
  "gf-hypothesis": [
    "competency",
    ["fluid-reasoning"],
    "moderate/strong/moderate",
    "Number of *distinguishable* hypotheses generated for an observation, and whether each specifies an observation that would rule it out.",
    "Hypothesis fluency without a discrimination step produces plausible stories rather than testable claims.",
    ["popper1959", "mayo1996", "klein1998"],
  ],
  "gf-novel-problem": [
    "competency",
    ["fluid-reasoning"],
    "moderate/moderate/emerging",
    "Solve rate on problems from an unfamiliar domain at a fixed difficulty, with time-to-first-viable-approach logged separately.",
    "Problem-solving heuristics are widely taught and their transfer is weak. Most measured improvement is domain knowledge in disguise.",
    ["polya1945", "newell1972", "barnett2002"],
  ],
  "gf-inductive": [
    "ability",
    ["fluid-reasoning"],
    "strong/moderate/emerging",
    "Rule-discovery tasks where you must state the rule *and* the disconfirming case you tested it against.",
    "Induction without deliberate disconfirmation reliably yields overconfident wrong rules — the standard result of Wason's rule-discovery task.",
    ["wason1968", "carroll1993", "popper1959"],
  ],

  // ── Fluid · Working Memory ────────────────────────────────────────────────
  "gwm-span": [
    "ability",
    ["working-memory"],
    "strong/emerging/speculative",
    "Complex span (operation or reading span) at a fixed difficulty, run at a consistent time of day.",
    "Span training reliably improves the trained task and very little else. Two large meta-analyses find no credible transfer to fluid intelligence; treat span gains as task learning.",
    ["baddeley2012", "melby2016", "shipstead2012", "simons2016"],
  ],
  "gwm-chunking": [
    "competency",
    ["working-memory", "crystallized-knowledge"],
    "strong/strong/emerging",
    "Recall of structured versus scrambled material in your domain — the gap between the two is the chunking, not the raw score.",
    "Chunking is domain knowledge, not capacity. Chess masters lose their advantage entirely on randomly placed pieces.",
    ["chase1973", "ericsson1995"],
  ],
  "gwm-updating": [
    "ability",
    ["working-memory", "executive-control"],
    "strong/moderate/emerging",
    "N-back or keep-track accuracy at a fixed load, with false alarms tracked separately from misses.",
    "Updating is a well-established executive function, but training it moves the trained paradigm far more than anything downstream of it.",
    ["miyake2000", "melby2016", "unsworth2014"],
  ],
  "gwm-mental-manipulation": [
    "ability",
    ["working-memory", "visual-processing"],
    "strong/moderate/emerging",
    "Multi-step mental arithmetic or spatial transformation with no external aid, scored for accuracy at a fixed step count.",
    "Manipulation capacity is tightly bound to the representation used. Gains in mental arithmetic do not appear in spatial manipulation.",
    ["baddeley2012", "carroll1993"],
  ],
  "gwm-dual-task": [
    "meta",
    ["working-memory", "executive-control"],
    "strong/moderate/emerging",
    "Performance cost when a secondary task is added, measured against your own single-task baseline.",
    "Almost all apparent multitasking is task switching with a real cost. The trainable part is recognising and avoiding the load, not raising the ceiling.",
    ["sweller1988", "vanmerrienboer2005", "ophir2009"],
  ],

  // ── Fluid · Processing Speed ──────────────────────────────────────────────
  "gs-perceptual-speed": [
    "ability",
    ["processing-speed"],
    "strong/moderate/speculative",
    "Symbol-search or digit-symbol style throughput under time pressure, with accuracy held constant.",
    "Processing speed is a robust and consequential individual difference, and one of the least trainable. Speed gains from practice are largely familiarity with the specific stimulus set.",
    ["salthouse1996", "carroll1993", "simons2016"],
  ],
  "gs-automaticity": [
    "competency",
    ["processing-speed"],
    "strong/strong/moderate",
    "Response time distribution on a well-practised task; automaticity shows as a collapse in variance, not just a lower mean.",
    "Automaticity is exquisitely specific to the practised stimulus-response mapping, and it makes errors harder to catch once established.",
    ["logan1988", "kellman2009"],
  ],
  "gs-scanning": [
    "ability",
    ["processing-speed", "visual-processing"],
    "strong/strong/emerging",
    "Search slope: how much your response time grows per additional distractor in the display.",
    "Visual search training is highly display-specific. Radiologists trained on one presentation format lose much of the advantage when it changes.",
    ["wolfe2010", "kellman2009"],
  ],
  "gs-decision-speed": [
    "ability",
    ["processing-speed", "executive-control"],
    "moderate/moderate/emerging",
    "Speed and accuracy together, ideally as a drift-diffusion style summary — one number for either alone is uninterpretable.",
    "You can always trade accuracy for speed. Any measurement that does not fix one while reporting the other is meaningless.",
    ["ratcliff2008", "heitz2014"],
  ],
  "gs-typing-fluency": [
    "competency",
    ["processing-speed", "psychomotor"],
    "strong/strong/moderate",
    "Words per minute at a fixed accuracy floor on unseen text, not on familiar drill passages.",
    "Input fluency removes friction between thought and page. It has no effect on the quality of the thought.",
    ["logan1988", "schmidt2011"],
    "physical",
  ],

  // ── Crystallized ──────────────────────────────────────────────────────────
  "gc-retrieval-practice": [
    "meta",
    ["learning-retrieval"],
    "strong/strong/strong",
    "Delayed unaided recall — the only score that matters is the one taken after a delay, not during the study session.",
    "Retrieval practice is among the best-supported techniques in learning science, but it strengthens what you retrieve. It cannot repair a bad selection of material.",
    ["roediger2006", "karpicke2008", "dunlosky2013"],
    "knowledge",
  ],
  "gc-spaced-repetition": [
    "meta",
    ["learning-retrieval"],
    "strong/strong/strong",
    "True retention rate at review (share of items recalled at first attempt), plus interval growth per item.",
    "Spacing works robustly, but scheduling software gives an illusion of control over material that was poorly formulated in the first place.",
    ["cepeda2006", "dunlosky2013", "fsrs"],
    "knowledge",
  ],
  "gc-elaboration": [
    "meta",
    ["learning-retrieval", "crystallized-knowledge"],
    "moderate/strong/moderate",
    "Explain why a fact is true without notes, then check the explanation against the source for errors you introduced.",
    "Elaborative interrogation helps most when you already have enough knowledge to elaborate with; for novices it can manufacture confident misconceptions.",
    ["dunlosky2013", "willingham2017"],
    "knowledge",
  ],
  "gc-interleaving": [
    "meta",
    ["learning-retrieval"],
    "strong/strong/moderate",
    "Performance on a mixed test containing problem types you did not know were coming, taken at least a day after practice.",
    "Interleaving reliably feels worse and works better. It slows within-session performance, which makes adherence the real difficulty.",
    ["rohrer2015", "soderstrom2015", "bjork1994"],
    "knowledge",
  ],
  "gc-memory-palace": [
    "competency",
    ["learning-retrieval", "visual-processing"],
    "strong/strong/emerging",
    "Ordered recall of an unseen list after a fixed encoding time, retested a week later.",
    "Mnemonic training produces dramatic, well-replicated gains on the trained list-learning task and does not raise general memory ability.",
    ["worthen2011", "dresler2017", "simons2016"],
    "knowledge",
  ],
  "gc-note-system": [
    "augmentation",
    ["crystallized-knowledge"],
    "emerging/moderate/emerging",
    "Retrieval success: how often you find the note you needed at the moment you needed it, counted rather than estimated.",
    "Note systems are widely evangelised on almost no controlled evidence. A system that is never read is an expensive filing habit.",
    ["ahrens2017", "clark1998", "risko2016"],
  ],
  "gc-mental-models": [
    "knowledge",
    ["crystallized-knowledge", "fluid-reasoning"],
    "emerging/moderate/emerging",
    "Apply a named model to an unseen case and state what it predicts that the obvious analysis does not.",
    "Collections of named models are easy to accumulate and hard to apply. Without a prediction step this becomes vocabulary, not understanding.",
    ["kahneman2011", "gick1983", "barnett2002"],
    "knowledge",
  ],
  "gc-knowledge-breadth": [
    "knowledge",
    ["crystallized-knowledge"],
    "strong/strong/moderate",
    "Unaided explanation of core ideas from fields outside your own, checked against a source afterwards.",
    "Breadth supports comprehension and analogy, but broad shallow knowledge is routinely mistaken for understanding, especially by its holder.",
    ["carroll1993", "willingham2017", "dunning2011"],
    "knowledge",
  ],
  "gc-domain-depth": [
    "knowledge",
    ["crystallized-knowledge"],
    "strong/strong/moderate",
    "Performance on representative domain tasks at professional difficulty, and the ability to recognise what you do not know within the domain.",
    "Depth is the single strongest predictor of performance within a domain and one of the weakest predictors outside it.",
    ["ericsson1993", "chase1973", "barnett2002"],
    "knowledge",
  ],
  "gc-transfer": [
    "meta",
    ["crystallized-knowledge", "fluid-reasoning"],
    "moderate/emerging/emerging",
    "Documented instances where something learned in one context solved a problem in a genuinely different one — recorded at the time, not recalled.",
    "Far transfer is rare and hard to produce deliberately. Neuron tracks it because it is the honest bar, not because it expects it often.",
    ["barnett2002", "gick1983", "salaGobet2019"],
  ],
  "gc-quantitative-literacy": [
    "knowledge",
    ["quantitative", "crystallized-knowledge"],
    "strong/strong/moderate",
    "Interpret an unseen statistic, chart or risk claim correctly, including stating what is missing from it.",
    "Statistical fluency is domain-transferable more than most knowledge, but it does not immunise anyone against motivated reasoning on topics they care about.",
    ["hoffrage2000", "gigerenzer1995", "tufte2001"],
    "knowledge",
  ],
  "gc-history-context": [
    "knowledge",
    ["crystallized-knowledge"],
    "strong/strong/moderate",
    "Explain a current situation's antecedents unaided, and name the counterexample that complicates your own account.",
    "Historical analogy is persuasive and frequently misleading. Superficial similarity between events is the default failure mode.",
    ["gick1983", "barnett2002"],
    "knowledge",
  ],
  "gc-technical-fluency": [
    "knowledge",
    ["crystallized-knowledge", "quantitative"],
    "strong/strong/moderate",
    "Read unfamiliar technical material in the domain and correctly state what it does and where it would fail.",
    "Technical vocabularies age fast. Fluency in a stack is a perishable asset, not a durable cognitive gain.",
    ["carroll1993", "ericsson1993"],
    "knowledge",
  ],
};
